import glossary from '@/glossary.json';

type Entry = { id: string; term: string; definition: string; see?: string[] };

const TERMS = (glossary as { terms: Entry[] }).terms;

/**
 * The whole glossary, on `/docs/glossary/`.
 *
 * Rendered from `glossary.json` rather than written out, so the page and the hover definitions cannot
 * disagree — they read the same file. The page that uses this is generated by `sync.mjs` and contains
 * nothing but the component tag.
 *
 * **Three columns, and each one earns its place.** An ordinal from a CSS counter, so the count is
 * legible at a glance and inserting a term renumbers the rest. The term in sans — it is a name, not an
 * identifier — with the identifier it corresponds to beside it in mono, which is the form you actually
 * type in a file. Then the meaning. Every definition starts at the same x, which is the whole reason a
 * glossary beats prose.
 *
 * **Every term is linkable.** Each carries `glossary-<id>`, the same anchor the hover card uses, so a
 * definition can be sent to somebody whether they arrived from a page or from here. The `#` appears on
 * hover and is focusable, like a heading's.
 *
 * Sorting is by the display term rather than by id, because that is the order a reader looks for
 * something in. `localeCompare` rather than `<`, so it is not case-sensitive.
 */
export function Glossary() {
  if (TERMS.length === 0) return <p className="muted">No terms defined yet.</p>;

  const sorted = [...TERMS].sort((a, b) => a.term.localeCompare(b.term));

  return (
    <dl className="glossary">
      {sorted.map((entry) => (
        <div className="glossary-row" key={entry.id}>
          <dt id={`glossary-${entry.id}`}>
            <span>{entry.term}</span>
            {/* The form that appears in a file. Quiet, and the thing you search for when editing. */}
            <span className="glossary-id">{entry.id}</span>
            <a
              className="glossary-anchor"
              href={`#glossary-${entry.id}`}
              aria-label={`Link to ${entry.term}`}
            >
              #
            </a>
          </dt>
          <dd>
            {entry.definition}
            {entry.see?.length ? (
              <span className="glossary-see">
                <span className="glossary-see-label">See also</span>
                {entry.see.map((other, i) => {
                  const target = TERMS.find((t) => t.id === other);
                  return (
                    <span key={other}>
                      {i > 0 ? ', ' : ''}
                      <a href={`#glossary-${other}`}>{target?.term ?? other}</a>
                    </span>
                  );
                })}
              </span>
            ) : null}
          </dd>
        </div>
      ))}
    </dl>
  );
}
