import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * A brand mark, inlined into the page.
 *
 * **Inlined rather than an `<img>`, and for the same reason the mod icons are.** The mark uses
 * `currentColor` for its ink and `var(--icon-ground)` for the knockout — the wordmark's gaps, the
 * hexagon's interior, Ko-fi's own capsule. An SVG loaded through `<img>` is a separate document with
 * **no access to the page's CSS**, so neither would resolve: the ink would fall back to black and the
 * ground to nothing, and the mark's interior would fill in solid. It would look correct in light mode,
 * which is exactly why it is not something to judge by eye.
 *
 * **This replaced a pair of files and four CSS rules.** There used to be `bisecthosting-light.svg` and
 * `-dark.svg` — the same artwork recoloured — with `[data-theme='dark']` and `:hover` rules switching
 * between two `<img>` elements. Once the mark takes its colour from the page there is one file, and the
 * switching has nothing left to do.
 *
 * **It takes the manifest's own entry now, and that closed a small lie.** The component used to read the
 * dimensions out of `manifest.sponsor` while hardcoding `bisecthosting.svg` as the filename — so
 * `sponsor.logo` was written in the manifest, validated by nothing, and read by nothing. With two marks
 * in the band that would have become two hardcoded names, so the entry itself is the argument: `logo` is
 * the path read, `logoWidth`/`logoHeight` are the ratio the box is reserved from.
 *
 * Both files are generated by `scripts/brand.mjs` and committed, like the icons. Read once per process
 * per file, not once per render.
 */

type Mark = {
  /** The public path the manifest gives, e.g. `/brand/kofi.svg`. */
  logo: string;
  /** The artwork's real width and height, so the box is reserved before the SVG is parsed. */
  logoWidth?: number;
  logoHeight?: number;
};

const cache = new Map<string, { body: string; viewBox: string } | null>();

function mark(entry: Mark) {
  const path = join(process.cwd(), 'public', entry.logo.replace(/^\//, ''));
  if (cache.has(path)) return cache.get(path) ?? null;

  let read: { body: string; viewBox: string } | null = null;
  try {
    const raw = readFileSync(path, 'utf8');
    read = {
      // Everything between the outer `<svg>` and its close, so React owns the element and its props.
      body: /<svg[^>]*>([\s\S]*)<\/svg>/.exec(raw)?.[1]?.trim() ?? '',
      viewBox: /viewBox="([^"]+)"/.exec(raw)?.[1] ?? '',
    };
  } catch {
    // No mark at all is better than a broken one, and the row still names the brand in words.
    read = null;
  }

  cache.set(path, read);
  return read;
}

/**
 * The mark, sized from its own aspect ratio.
 *
 * **The box comes from the entry, and that is one place per mark rather than two.** `logoHeight` is the
 * height the mark is drawn at and `logoWidth`/`logoHeight` is the ratio the width is derived from — so
 * the host is drawn at 123x41 and the tip jar at 124x34, and neither number is repeated in the component
 * that draws it. It used to be a `height` prop on every call with 41 as the default, which was the same
 * decision written twice, and it could not express two marks at different sizes without a third copy.
 *
 * Setting both attributes rather than leaving the width to `auto` means the box is reserved before the
 * SVG is parsed, so nothing shifts. The ratio is the artwork's own — the file's viewBox and the box here
 * agree to within a rounding pixel, and an SVG with a viewBox letterboxes rather than stretches, so the
 * difference is a fraction of a pixel rather than a distortion.
 *
 * `height` is still a prop for a caller that needs the mark at another size; the ratio decides the width
 * either way. `check.mjs` holds the rendered box to what the manifest says.
 */
export function BrandMark({ entry, height }: { entry: Mark; height?: number }) {
  const m = mark(entry);
  if (!m) return null;

  const drawn = height ?? entry.logoHeight ?? 41;
  const ratio = (entry.logoWidth ?? 123) / (entry.logoHeight ?? 41);

  return (
    <svg
      className="brand-mark"
      width={Math.round(drawn * ratio)}
      height={drawn}
      viewBox={m.viewBox}
      fill="none"
      aria-hidden="true"
      // Raw SVG from a file this repository generates, not user content — nothing here can carry a script.
      dangerouslySetInnerHTML={{ __html: m.body }}
    />
  );
}
