import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import manifest from '@/manifest.json';

/**
 * The host's mark, inlined into the page.
 *
 * **Inlined rather than an `<img>`, and for the same reason the mod icons are.** The mark uses
 * `currentColor` for its ink and `var(--icon-ground)` for the knockout — the wordmark's gaps and the
 * hexagon's interior. An SVG loaded through `<img>` is a separate document with **no access to the page's
 * CSS**, so neither would resolve: the ink would fall back to black and the ground to nothing, and the
 * hexagon's interior would fill in solid. It would look correct in light mode, which is exactly why it is
 * not something to judge by eye.
 *
 * **This replaced a pair of files and four CSS rules.** There used to be `bisecthosting-light.svg` and
 * `-dark.svg` — the same artwork recoloured — with `[data-theme='dark']` and `:hover` rules switching
 * between two `<img>` elements. Once the mark takes its colour from the page there is one file, and the
 * switching has nothing left to do.
 *
 * The file is generated by `scripts/brand.mjs` from `design/brand-source/bisecthosting.svg` and is
 * committed, like the icons. Read once per process, not once per render.
 */

let cached: { body: string; viewBox: string } | null | undefined;

function mark() {
  if (cached !== undefined) return cached;

  const path = join(process.cwd(), 'public', 'brand', 'bisecthosting.svg');
  try {
    const raw = readFileSync(path, 'utf8');
    cached = {
      // Everything between the outer `<svg>` and its close, so React owns the element and its props.
      body: /<svg[^>]*>([\s\S]*)<\/svg>/.exec(raw)?.[1]?.trim() ?? '',
      viewBox: /viewBox="([^"]+)"/.exec(raw)?.[1] ?? '0 0 243.7 81.21',
    };
  } catch {
    // No mark at all is better than a broken one, and the band still says who the host is in words.
    cached = null;
  }

  return cached;
}

/**
 * The mark, sized from its own aspect ratio.
 *
 * `height` is the only knob, and the width is derived from the manifest's `logoWidth`/`logoHeight` — the
 * real ratio of the artwork, 243.7 × 81.21. Setting both explicitly rather than leaving the width to
 * `auto` means the box is reserved before the SVG is parsed, so nothing shifts. The numbers live in the
 * manifest because they come from the file, not from a design decision.
 */
export function BrandMark({ height = 41 }: { height?: number }) {
  const m = mark();
  if (!m) return null;

  const sponsor = (manifest as { sponsor?: { logoWidth?: number; logoHeight?: number } }).sponsor;
  const ratio = (sponsor?.logoWidth ?? 123) / (sponsor?.logoHeight ?? 41);

  return (
    <svg
      className="brand-mark"
      width={Math.round(height * ratio)}
      height={height}
      viewBox={m.viewBox}
      fill="none"
      aria-hidden="true"
      // Raw SVG from a file this repository generates, not user content — nothing here can carry a script.
      dangerouslySetInnerHTML={{ __html: m.body }}
    />
  );
}
