import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * A mod's mark, inlined into the page.
 *
 * **Inlined rather than an `<img>`, and that is not a style preference.** Each glyph uses two CSS
 * variables: `currentColor` for the ink and `var(--icon-ground)` for the knockouts. An SVG loaded through
 * `<img>` is a separate document with **no access to the page's CSS**, so neither variable would resolve
 * — `currentColor` would fall back to black and the knockouts to nothing. The icons would be black on a
 * dark page and their inner detail would vanish. Inlining is the only version that works in both themes
 * from one file.
 *
 * The files themselves are generated by `scripts/_icons.mjs`, which strips the background plate, maps the
 * palette to `currentColor` at ranked opacities, and points the white knockouts at `--icon-ground`. They
 * are committed, like the brand logos.
 *
 * **`--icon-ground` is set by the component, not by the SVG.** It defaults to `--bg`, and any context
 * whose ground inverts on hover overrides it. That is the whole reason it is a separate token from
 * `--bg`: the catalog's cells invert to `--inv-bg`, and a knockout pointing at `--bg` would then reveal a
 * colour that is not behind it.
 *
 * `aria-hidden` on the wrapper and nothing on the inner markup: the mod's name is always beside the icon,
 * so an accessible name would have it announced twice.
 */

/**
 * Files are read once per process rather than once per render.
 *
 * `readFileSync` on every cell of every page is a syscall per icon per render, and there are six mods on
 * the catalog plus a section per mod in every docs sidebar. The cache is a module-level Map because the
 * build is a single process — on a server this would need to be keyed on something, and on a static
 * export it does not.
 */
const cache = new Map<string, string | null>();

function inner(id: string): string | null {
  if (cache.has(id)) return cache.get(id) ?? null;

  let svg: string | null = null;
  try {
    const raw = readFileSync(join(process.cwd(), 'public', 'icons', `${id}.svg`), 'utf8');
    // Everything between the outer `<svg ...>` and its close, so React owns the element and its props.
    svg = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(raw)?.[1]?.trim() ?? null;
  } catch {
    // A mod with no icon is a normal state, not an error -- see the placeholder below.
    svg = null;
  }

  cache.set(id, svg);
  return svg;
}

const SIZES = { sm: 16, md: 20, lg: 32, xl: 48 } as const;

export function ModIcon({
  id,
  size = 'md',
  className = '',
}: {
  id: string;
  size?: keyof typeof SIZES;
  className?: string;
}) {
  const px = SIZES[size];
  const body = inner(id);

  /*
   * No icon yet.
   *
   * A dashed square the same size as the real marks rather than nothing at all, because the alternative
   * is a row that silently shifts left and a reader who cannot tell whether the icon is missing or the
   * mod is different. A visible empty slot is honest about being a slot.
   *
   * The same principle as a Modrinth link that is typed but not yet a link: show the gap, do not hide it.
   */
  /*
   * The class string is built conditionally rather than interpolated.
   *
   * `` `mod-icon ${className}` `` with an empty `className` renders `class="mod-icon "` — a trailing
   * space in every glyph on the site. Harmless, and untidy enough to notice when reading the built HTML,
   * which is where it was spotted.
   */
  const classes = (extra: string) => (extra ? `mod-icon ${extra}` : 'mod-icon');

  if (!body) {
    return (
      <span
        className={classes(`mod-icon-empty ${className}`.trim())}
        style={{ width: px, height: px }}
        aria-hidden="true"
      />
    );
  }

  return (
    <svg
      className={classes(className)}
      style={{ width: px, height: px }}
      viewBox="0 0 256 256"
      fill="none"
      aria-hidden="true"
      // The glyph is raw SVG from a file this repository generates, not user content, so there is
      // nothing here that could carry a script.
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
